### PR TITLE
Add Pre HTML area

### PR DESCRIPTION
**Pull request by caesar2164**
@stvstnfrd add pre HTML area.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
I'm a bit worried about feature creep here.

If we can cover enough bases by just allowing `pre_text`,
that seems like it would cover the spirit of what we're doing here.

I'd prefer to avoid adding HTML editing here because the ImageModal HTML editor would never be as good as the proper HTML editor tool.

**Comment by caesar2164** [comment]
@stvstnfrd ok converted to just having the one HTML area

**Comment by stvstnfrd** [comment]
@caesar2164 My UX concerns have not yet been addressed.

There are a few glaring issues here:
- Input is raw; there's no WYSIWYG editor.
  Users of our site are conditioned to expect a graphical editor when
  inserting HTML.
  While this feature, as is, would allow _us_, _internally_, to
  copy/paste to import existing markup, it's pretty much unusable to
  the lay-person. I don't expect many of our users to be proficient in
  writing raw HTML. This is particularly a pain because:
- There's no validation of markup.
  If a closing tag is omitted, the entire may page break. Users may not
  know how to diagnose and then the support burden on us and CourseOps
  is increased. And since there's no WYSIWYG:
- Users would have to
  repeatedly save the problem to preview it in Studio.

If we include HTML input directly in this component, I expect this to be
the tool people reach for instinctively, instead of the superior,
dedicated HTML editor. This feels like a step backward w/r/t usability.

As is, I'm seeing lots of risk and little-to-no reward.

Can you point me to related examples in the wild of a component that
would benefit from this?

**Comment by stvstnfrd** [comment]
Let me know if it's easier to discuss F2F,
but please do point me to some of the relevant examples in the wild.

**Comment by stvstnfrd** [comment]
Closing since we've discussed other plans.

**Pull request closed without merging**
