### PR TITLE
Implement xblock-utils default studio editor

### PR DESCRIPTION
**Pull request by stvstnfrd**
This did not yet exist when this custom editor logic was created.
xblock-utils provides a superior solution, so we should adopt it.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@azimpradhan Thanks for the help! Mind taking a quick look?

**Comment by stvstnfrd** [comment]
Display names added at 4e444b6

`editable_fields` does work as a list; it just needs to be an iterable [1]

Added i18n to text at d164dda

[1] https://github.com/edx/xblock-utils/blob/08e5a5a9fc8ab46b627435427fd7e04c20809009/xblockutils/studio_editable.py#L82

**Comment by stvstnfrd** [comment]
I will squash this before merging.

**Comment by stvstnfrd** [comment]
Actually, I'll keep the i18n commit separate.

**Comment by stvstnfrd** [comment]
@azimpradhan Feedback addressed.

**Comment by azimpradhan** [comment]
@stvstnfrd, +1

**Pull request merged**
