### PR TITLE
Add optional description attribute

### PR DESCRIPTION
**Pull request by stvstnfrd**
This improves accessibility for screen readers.

### CODE REVIEW

**Comment by stvstnfrd** [comment]
@caesar2164

**Comment by stvstnfrd** [comment]
Once this merges, I'll:
- create a new git tag
- upload to PyPi
- update the version number in a platform PR for requirements.txt

**Comment by caesar2164** [comment]
I like it! :+1:

**Comment by stvstnfrd** [comment]
@azimpradhan This was sooo much easier to add a new field after switching to xblockutils!

**Pull request merged**
