### PR TITLE
Add Mobile Support

### PR DESCRIPTION
**Pull request by libremente**
Decorated the student view with the XBlocks_supports for multi_device
in order to solve the compatibility issue with mobile handheld devices.

@stvstnfrd @caesar2164 @caseylitton

### CODE REVIEW

**Comment by caesar2164** [comment]
👍

**Comment by caseylitton** [comment]
Changes look good.  Per our conversation about free text xblock, check if any settings in the studio view affect the UI for the image modal.  I think we covered all the possibilities in the free text however.

**Comment by libremente** [comment]
> check if any settings in the studio view affect the UI for the image modal.

Ok I will let you know. Thanks.

**Comment by stvstnfrd** [comment]
+1

**Pull request merged**
